apiVersion: apps/v1
kind: Deployment
metadata:
  name: sys-stats
  namespace: 'smartcow-ns'
  labels:
    application: sys-stats
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      application: sys-stats
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        application: sys-stats
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 15
      containers:
      - name: sys-stats
        image: sys-stats-image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: sys-stats-port
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 512Mi
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 2
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 2
          successThreshold: 2
          tcpSocket:
            port: 80
          timeoutSeconds: 2